services:
  - type: web
    name: anilex-backend
    runtime: node
    plan: free
    region: frankfurt
    autoDeploy: true
    buildCommand: npm install
    startCommand: node --experimental-sqlite server/index.js
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: NODE_OPTIONS
        value: "--experimental-sqlite"
      - key: PORT
        value: 10000
